Repository PuppyMode-org/PuppyMode-Server, pull requests merged in 2025-01, with the labels that each got.

#4 [CI] CICD 파이프라인 구축
  .github/workflows/cicd.yml
  Dockerfile
  build.gradle
Labels: 🚀 ci

#6 Feat/#5 querydsl setup
  .gitignore
  build.gradle
  src/main/java/umc/puppymode/config/QueryDSLConfig.java
  src/main/java/umc/puppymode/domain/Puppy.java
  src/main/java/umc/puppymode/domain/PuppyLevel.java
  src/main/java/umc/puppymode/domain/User.java
  src/main/java/umc/puppymode/domain/UserAlarmType.java
  src/main/java/umc/puppymode/domain/UserPolicyType.java
  src/main/java/umc/puppymode/domain/enums/CustomizingItem.java
  src/main/java/umc/puppymode/domain/enums/FeedingItem.java
  src/main/java/umc/puppymode/domain/enums/PuppyType.java
  src/main/java/umc/puppymode/domain/mapping/UserAlarm.java
  src/main/java/umc/puppymode/domain/mapping/UserPolicy.java
Labels: ✨ feature

#8 [BUG] build.gradle 수정 #7
  build.gradle
Labels: 🐛 bug

#10 Feat/#9 notification settings
  src/main/java/umc/puppymode/apiPayload/code/status/ErrorStatus.java
  src/main/java/umc/puppymode/domain/NotificationCategory.java
  src/main/java/umc/puppymode/domain/User.java
  src/main/java/umc/puppymode/domain/mapping/UserNotification.java
  src/main/java/umc/puppymode/repository/UserRepository.java
  src/main/java/umc/puppymode/service/UserService/UserCommandService.java
  src/main/java/umc/puppymode/service/UserService/UserCommandServiceImpl.java
  src/main/java/umc/puppymode/service/UserService/UserQueryService.java
  src/main/java/umc/puppymode/service/UserService/UserQueryServiceImpl.java
  src/main/java/umc/puppymode/web/controller/UserController.java
  src/main/java/umc/puppymode/web/dto/UserRequestDTO.java
  src/main/java/umc/puppymode/web/dto/UserResponseDTO.java
Labels: ✨ feature

#17 Feat/#11 user push notification
  .gitignore
  build.gradle
  src/main/java/umc/puppymode/PuppymodeApplication.java
  src/main/java/umc/puppymode/apiPayload/code/status/ErrorStatus.java
  src/main/java/umc/puppymode/domain/User.java
  src/main/java/umc/puppymode/repository/UserRepository.java
  src/main/java/umc/puppymode/service/FcmService/FcmAppointmentService.java
  src/main/java/umc/puppymode/service/FcmService/FcmAppointmentServiceImpl.java
  src/main/java/umc/puppymode/service/FcmService/FcmPlaytimeService.java
  src/main/java/umc/puppymode/service/FcmService/FcmPlaytimeServiceImpl.java
  src/main/java/umc/puppymode/service/FcmService/FcmService.java
  src/main/java/umc/puppymode/service/FcmService/FcmServiceImpl.java
  src/main/java/umc/puppymode/service/UserService/UserQueryService.java
  src/main/java/umc/puppymode/service/UserService/UserQueryServiceImpl.java
  src/main/java/umc/puppymode/util/DistanceCalculator.java
  src/main/java/umc/puppymode/util/RandomMessages.java
  src/main/java/umc/puppymode/web/controller/FcmController.java
  src/main/java/umc/puppymode/web/dto/FCMAppointmentRequestDTO.java
  src/main/java/umc/puppymode/web/dto/FCMPlayRequestDTO.java
  src/main/java/umc/puppymode/web/dto/FCMPlayResponseDTO.java
  src/main/java/umc/puppymode/web/dto/FCMRequestDTO.java
  src/main/java/umc/puppymode/web/dto/FCMResponseDTO.java
Labels: ✨ feature

#18 Feat/#13 drinking appointment
  build.gradle
  src/main/java/umc/puppymode/apiPayload/ApiResponse.java
  src/main/java/umc/puppymode/apiPayload/code/status/ErrorStatus.java
  src/main/java/umc/puppymode/apiPayload/code/status/SuccessStatus.java
  src/main/java/umc/puppymode/converter/DrinkingAppointmentConverter.java
  src/main/java/umc/puppymode/domain/DrinkingAppointment.java
  src/main/java/umc/puppymode/domain/enums/AppointmentStatus.java
  src/main/java/umc/puppymode/repository/DrinkingAppointmentRepository.java
  src/main/java/umc/puppymode/service/DrinkingAppointmentService/DrinkingAppointmentCommendService.java
  src/main/java/umc/puppymode/service/DrinkingAppointmentService/DrinkingAppointmentCommendServiceImpl.java
  src/main/java/umc/puppymode/service/DrinkingAppointmentService/DrinkingAppointmentQueryService.java
  src/main/java/umc/puppymode/service/DrinkingAppointmentService/DrinkingAppointmentQueryServiceImpl.java
  src/main/java/umc/puppymode/web/controller/DrinkingAppointmentController.java
  src/main/java/umc/puppymode/web/dto/DrinkingAppointmentRequestDTO.java
  src/main/java/umc/puppymode/web/dto/DrinkingAppointmentResponseDTO.java
Labels: ✨ feature

#20 Feat/#13 drinking appointment
  build.gradle
  src/main/java/umc/puppymode/apiPayload/ApiResponse.java
  src/main/java/umc/puppymode/apiPayload/code/status/ErrorStatus.java
  src/main/java/umc/puppymode/apiPayload/code/status/SuccessStatus.java
  src/main/java/umc/puppymode/converter/DrinkingAppointmentConverter.java
  src/main/java/umc/puppymode/domain/DrinkingAppointment.java
  src/main/java/umc/puppymode/domain/enums/AppointmentStatus.java
  src/main/java/umc/puppymode/repository/DrinkingAppointmentRepository.java
  src/main/java/umc/puppymode/service/DrinkingAppointmentService/DrinkingAppointmentCommendService.java
  src/main/java/umc/puppymode/service/DrinkingAppointmentService/DrinkingAppointmentCommendServiceImpl.java
  src/main/java/umc/puppymode/service/DrinkingAppointmentService/DrinkingAppointmentQueryService.java
  src/main/java/umc/puppymode/service/DrinkingAppointmentService/DrinkingAppointmentQueryServiceImpl.java
  src/main/java/umc/puppymode/web/controller/DrinkingAppointmentController.java
  src/main/java/umc/puppymode/web/dto/DrinkingAppointmentRequestDTO.java
  src/main/java/umc/puppymode/web/dto/DrinkingAppointmentResponseDTO.java
Labels: ✨ feature

#22 [FEAT] 메인 뷰 강아지 관련 기능 구현 #15
  .github/workflows/cicd.yml
  src/main/java/umc/puppymode/apiPayload/code/status/ErrorStatus.java
  src/main/java/umc/puppymode/converter/MainPuppyConverter.java
  src/main/java/umc/puppymode/domain/Puppy.java
  src/main/java/umc/puppymode/domain/PuppyLevel.java
  src/main/java/umc/puppymode/domain/User.java
  src/main/java/umc/puppymode/domain/enums/PuppyType.java
  src/main/java/umc/puppymode/repository/PuppyRepository.java
  src/main/java/umc/puppymode/service/MainPuppyService/MainPuppyCommandService.java
  src/main/java/umc/puppymode/service/MainPuppyService/MainPuppyCommandServiceImpl.java
  src/main/java/umc/puppymode/service/MainPuppyService/MainPuppyQueryService.java
  src/main/java/umc/puppymode/service/MainPuppyService/MainPuppyQueryServiceImpl.java
  src/main/java/umc/puppymode/web/controller/MainPuppyController.java
  src/main/java/umc/puppymode/web/dto/MainPuppyDTO/MainPuppyResDTO.java
Labels: ✨ feature

#24 [FEAT] 음주 중 관련 기능 구현 #19
  build.gradle
  src/main/java/umc/puppymode/apiPayload/ApiResponse.java
  src/main/java/umc/puppymode/apiPayload/code/status/ErrorStatus.java
  src/main/java/umc/puppymode/apiPayload/code/status/SuccessStatus.java
  src/main/java/umc/puppymode/converter/DrinkingAppointmentConverter.java
  src/main/java/umc/puppymode/domain/DrinkingAppointment.java
  src/main/java/umc/puppymode/domain/enums/AppointmentStatus.java
  src/main/java/umc/puppymode/repository/DrinkingAppointmentRepository.java
  src/main/java/umc/puppymode/service/DrinkingAppointmentService/DrinkingAppointmentCommendService.java
  src/main/java/umc/puppymode/service/DrinkingAppointmentService/DrinkingAppointmentCommendServiceImpl.java
  src/main/java/umc/puppymode/service/DrinkingAppointmentService/DrinkingAppointmentQueryService.java
  src/main/java/umc/puppymode/service/DrinkingAppointmentService/DrinkingAppointmentQueryServiceImpl.java
  src/main/java/umc/puppymode/service/LocationService/LocationService.java
  src/main/java/umc/puppymode/service/LocationService/LocationServiceImpl.java
  src/main/java/umc/puppymode/web/controller/DrinkingAppointmentController.java
  src/main/java/umc/puppymode/web/controller/LocationController.java
  src/main/java/umc/puppymode/web/dto/DrinkingAppointmentRequestDTO.java
  src/main/java/umc/puppymode/web/dto/DrinkingAppointmentResponseDTO.java
  src/main/java/umc/puppymode/web/dto/LocationRequestDTO.java
  src/main/java/umc/puppymode/web/dto/LocationResponseDTO.java
Labels: ✨ feature

#27 Feat/#19 drinking in progress
  src/main/java/umc/puppymode/apiPayload/code/status/SuccessStatus.java
  src/main/java/umc/puppymode/service/DrinkingAppointmentService/DrinkingAppointmentCommendService.java
  src/main/java/umc/puppymode/service/DrinkingAppointmentService/DrinkingAppointmentCommendServiceImpl.java
  src/main/java/umc/puppymode/service/DrinkingAppointmentService/DrinkingAppointmentQueryService.java
  src/main/java/umc/puppymode/service/DrinkingAppointmentService/DrinkingAppointmentQueryServiceImpl.java
  src/main/java/umc/puppymode/service/LocationService/LocationService.java
  src/main/java/umc/puppymode/service/LocationService/LocationServiceImpl.java
  src/main/java/umc/puppymode/web/controller/DrinkingAppointmentController.java
  src/main/java/umc/puppymode/web/controller/LocationController.java
  src/main/java/umc/puppymode/web/dto/DrinkingAppointmentRequestDTO.java
  src/main/java/umc/puppymode/web/dto/DrinkingAppointmentResponseDTO.java
  src/main/java/umc/puppymode/web/dto/LocationRequestDTO.java
  src/main/java/umc/puppymode/web/dto/LocationResponseDTO.java
Labels: ✨ feature

#26 [FEAT] 음주 기록 관련 API 구현 #14
  src/main/java/umc/puppymode/domain/DrinkCategory.java
  src/main/java/umc/puppymode/domain/DrinkItem.java
  src/main/java/umc/puppymode/domain/HangoverItem.java
  src/main/java/umc/puppymode/repository/DrinkCategoryRepository.java
  src/main/java/umc/puppymode/repository/HangoverRepository.java
  src/main/java/umc/puppymode/service/DrinkService/DrinkCommandService.java
  src/main/java/umc/puppymode/service/DrinkService/DrinkCommandServiceImpl.java
  src/main/java/umc/puppymode/service/DrinkService/DrinkQueryService.java
  src/main/java/umc/puppymode/service/DrinkService/DrinkQueryServiceImpl.java
  src/main/java/umc/puppymode/web/controller/DrinkController.java
  src/main/java/umc/puppymode/web/dto/DrinkRequestDTO.java
  src/main/java/umc/puppymode/web/dto/DrinkResponseDTO.java
Labels: ✨ feature

#28 Feat/#21 notification actual values
  src/main/java/umc/puppymode/repository/PuppyRepository.java
  src/main/java/umc/puppymode/repository/UserRepository.java
  src/main/java/umc/puppymode/service/FcmService/FcmAppointmentServiceImpl.java
  src/main/java/umc/puppymode/service/FcmService/FcmPlaytimeService.java
  src/main/java/umc/puppymode/service/FcmService/FcmPlaytimeServiceImpl.java
  src/main/java/umc/puppymode/service/UserService/UserQueryService.java
  src/main/java/umc/puppymode/service/UserService/UserQueryServiceImpl.java
  src/main/java/umc/puppymode/web/controller/FcmController.java
  src/main/java/umc/puppymode/web/dto/FCMAppointmentRequestDTO.java
Labels: ✨ feature

#29 [Feat] AWS S3 이미지 파일 업로드 구현 #25
  build.gradle
  src/main/java/umc/puppymode/apiPayload/code/status/ErrorStatus.java
  src/main/java/umc/puppymode/config/AwsS3Config.java
  src/main/java/umc/puppymode/service/AwsS3Service/AwsS3Service.java
  src/main/java/umc/puppymode/service/AwsS3Service/AwsS3ServiceImpl.java
  src/main/java/umc/puppymode/web/controller/AwsS3Controller.java
Labels: ✨ feature

#36 Feat/#31 drinking status
  src/main/java/umc/puppymode/apiPayload/code/status/SuccessStatus.java
  src/main/java/umc/puppymode/domain/enums/AppointmentStatus.java
  src/main/java/umc/puppymode/repository/DrinkingAppointmentRepository.java
  src/main/java/umc/puppymode/service/DrinkingAppointmentService/DrinkingAppointmentCommendService.java
  src/main/java/umc/puppymode/service/DrinkingAppointmentService/DrinkingAppointmentCommendServiceImpl.java
  src/main/java/umc/puppymode/service/DrinkingAppointmentService/DrinkingAppointmentQueryService.java
  src/main/java/umc/puppymode/service/DrinkingAppointmentService/DrinkingAppointmentQueryServiceImpl.java
  src/main/java/umc/puppymode/service/LocationService/LocationService.java
  src/main/java/umc/puppymode/service/LocationService/LocationServiceImpl.java
  src/main/java/umc/puppymode/web/controller/DrinkingAppointmentController.java
  src/main/java/umc/puppymode/web/dto/DrinkingAppointmentRequestDTO.java
  src/main/java/umc/puppymode/web/dto/DrinkingAppointmentResponseDTO.java
Labels: ✨ feature

#38 [FEAT] 강아지 아이템 API 수정 #34
  src/main/java/umc/puppymode/domain/EquippedItemImage.java
  src/main/java/umc/puppymode/domain/PuppyItem.java
  src/main/java/umc/puppymode/domain/mapping/PuppyCustomization.java
  src/main/java/umc/puppymode/repository/EquippedItemImageRepository.java
  src/main/java/umc/puppymode/repository/PuppyCustomizationRepository.java
  src/main/java/umc/puppymode/service/PuppyService/PuppyItemService.java
  src/main/java/umc/puppymode/service/PuppyService/PuppyItemServiceImpl.java
  src/main/java/umc/puppymode/web/controller/PuppyItemController.java
  src/main/java/umc/puppymode/web/dto/ItemCategoryResponseDTO.java
  src/main/java/umc/puppymode/web/dto/ItemResponseDTO.java
Labels: ✨ feature

#37 Feat/#12 spring security
  build.gradle
  src/main/java/umc/puppymode/config/security/CustomAccessDeniedHandler.java
  src/main/java/umc/puppymode/config/security/CustomJwtAuthenticationEntryPoint.java
  src/main/java/umc/puppymode/config/security/JwtAuthenticationFilter.java
  src/main/java/umc/puppymode/config/security/JwtTokenProvider.java
  src/main/java/umc/puppymode/config/security/JwtValidationType.java
  src/main/java/umc/puppymode/config/security/SecurityConfig.java
  src/main/java/umc/puppymode/config/security/UserAuthentication.java
  src/main/java/umc/puppymode/domain/User.java
  src/main/java/umc/puppymode/repository/UserRepository.java
  src/main/java/umc/puppymode/service/AuthService/KakaoService.java
  src/main/java/umc/puppymode/service/UserService/UserAuthService.java
  src/main/java/umc/puppymode/service/UserService/UserAuthServiceImpl.java
  src/main/java/umc/puppymode/service/UserService/UserCommandServiceImpl.java
  src/main/java/umc/puppymode/web/controller/KakaoLoginController.java
  src/main/java/umc/puppymode/web/dto/KakaoTokenResponseDTO.java
  src/main/java/umc/puppymode/web/dto/KakaoUserInfoResponseDTO.java
  src/main/java/umc/puppymode/web/dto/LoginResponseDTO.java
Labels: ✨ feature

#41 [Feat] 강아지 랜덤 선택 기능 수정 #32
  src/main/java/umc/puppymode/converter/MainPuppyConverter.java
  src/main/java/umc/puppymode/domain/Puppy.java
  src/main/java/umc/puppymode/repository/PuppyLevelRepository.java
  src/main/java/umc/puppymode/service/FcmService/FcmPlaytimeServiceImpl.java
  src/main/java/umc/puppymode/service/MainPuppyService/MainPuppyCommandService.java
  src/main/java/umc/puppymode/service/MainPuppyService/MainPuppyCommandServiceImpl.java
  src/main/java/umc/puppymode/web/controller/MainPuppyController.java
  src/main/java/umc/puppymode/web/dto/MainPuppyDTO/MainPuppyResDTO.java
Labels: ✨ feature

#42 [REFACTOR] 알림 수신 여부 관련 API에서 JWT로 user id 추출 #40
  src/main/java/umc/puppymode/service/UserService/UserAuthService.java
  src/main/java/umc/puppymode/service/UserService/UserAuthServiceImpl.java
  src/main/java/umc/puppymode/web/controller/UserController.java
Labels: ♻️ refactor

#43 [FEAT] 음주 기록 관련 API 구현 #30
  src/main/java/umc/puppymode/apiPayload/code/status/ErrorStatus.java
  src/main/java/umc/puppymode/domain/DrinkHistory.java
  src/main/java/umc/puppymode/domain/DrinkHistoryItem.java
  src/main/java/umc/puppymode/domain/Feed.java
  src/main/java/umc/puppymode/domain/enums/FeedingItem.java
  src/main/java/umc/puppymode/repository/DrinkHistoryItemRepository.java
  src/main/java/umc/puppymode/repository/DrinkHistoryRepository.java
  src/main/java/umc/puppymode/repository/DrinkItemRepository.java
  src/main/java/umc/puppymode/repository/FeedRepository.java
  src/main/java/umc/puppymode/service/DrinkService/DrinkCommandService.java
  src/main/java/umc/puppymode/service/DrinkService/DrinkCommandServiceImpl.java
  src/main/java/umc/puppymode/service/DrinkService/DrinkQueryServiceImpl.java
  src/main/java/umc/puppymode/web/controller/DrinkController.java
  src/main/java/umc/puppymode/web/dto/DrinkRequestDTO.java
  src/main/java/umc/puppymode/web/dto/DrinkResponseDTO.java
Labels: ✨ feature

#48 [Feat] 컬렉션 조회 기능 구현 #44
  src/main/java/umc/puppymode/converter/CollectionConverter.java
  src/main/java/umc/puppymode/converter/MainPuppyConverter.java
  src/main/java/umc/puppymode/domain/Collection.java
  src/main/java/umc/puppymode/domain/Puppy.java
  src/main/java/umc/puppymode/domain/PuppyLevel.java
  src/main/java/umc/puppymode/repository/CollectionRepository.java
  src/main/java/umc/puppymode/service/CollectionService/CollectionQueryService.java
  src/main/java/umc/puppymode/service/CollectionService/CollectionQueryServiceImpl.java
  src/main/java/umc/puppymode/service/MainPuppyService/MainPuppyCommandServiceImpl.java
  src/main/java/umc/puppymode/web/controller/CollectionController.java
  src/main/java/umc/puppymode/web/dto/CollectionDTO/CollectionResDTO.java
Labels: ✨ feature

#53 Refactor/#52 puppy custom jwt
  src/main/java/umc/puppymode/domain/PuppyItem.java
  src/main/java/umc/puppymode/domain/mapping/PuppyCustomization.java
  src/main/java/umc/puppymode/repository/PuppyCustomizationRepository.java
  src/main/java/umc/puppymode/service/PuppyService/PuppyItemService.java
  src/main/java/umc/puppymode/service/PuppyService/PuppyItemServiceImpl.java
  src/main/java/umc/puppymode/web/controller/PuppyItemController.java
Labels: ♻️ refactor

#55 [Refactor] 메인강아지 및 컬렉션 JWT 사용 수정 #54
  src/main/java/umc/puppymode/apiPayload/code/status/ErrorStatus.java
  src/main/java/umc/puppymode/service/MainPuppyService/MainPuppyCommandService.java
  src/main/java/umc/puppymode/service/MainPuppyService/MainPuppyCommandServiceImpl.java
  src/main/java/umc/puppymode/web/controller/CollectionController.java
  src/main/java/umc/puppymode/web/controller/MainPuppyController.java
Labels: ♻️ refactor

#62 Refactor/#58 delete current location
  src/main/java/umc/puppymode/service/DrinkingAppointmentService/DrinkingAppointmentCommendServiceImpl.java
  src/main/java/umc/puppymode/web/controller/LocationController.java
  src/main/java/umc/puppymode/web/dto/LocationRequestDTO.java
  src/main/java/umc/puppymode/web/dto/LocationResponseDTO.java
Labels: ♻️ refactor

#64 Feature/#50 manage fcm token
  src/main/java/umc/puppymode/config/AsyncConfig.java
  src/main/java/umc/puppymode/config/RestTemplateConfig.java
  src/main/java/umc/puppymode/domain/Token.java
  src/main/java/umc/puppymode/domain/User.java
  src/main/java/umc/puppymode/domain/enums/TokenType.java
  src/main/java/umc/puppymode/repository/DrinkingAppointmentRepository.java
  src/main/java/umc/puppymode/repository/PuppyRepository.java
  src/main/java/umc/puppymode/repository/TokenRepository.java
  src/main/java/umc/puppymode/repository/UserRepository.java
  src/main/java/umc/puppymode/service/FcmService/FcmAppointmentService.java
  src/main/java/umc/puppymode/service/FcmService/FcmAppointmentServiceImpl.java
  src/main/java/umc/puppymode/service/FcmService/FcmPlaytimeService.java
  src/main/java/umc/puppymode/service/FcmService/FcmPlaytimeServiceImpl.java
  src/main/java/umc/puppymode/service/FcmService/FcmQueryService.java
  src/main/java/umc/puppymode/service/FcmService/FcmQueryServiceImpl.java
  src/main/java/umc/puppymode/service/FcmService/FcmService.java
  src/main/java/umc/puppymode/service/FcmService/FcmServiceImpl.java
  src/main/java/umc/puppymode/service/UserService/UserAuthService.java
  src/main/java/umc/puppymode/service/UserService/UserAuthServiceImpl.java
  src/main/java/umc/puppymode/service/UserService/UserQueryService.java
  src/main/java/umc/puppymode/service/UserService/UserQueryServiceImpl.java
  src/main/java/umc/puppymode/web/controller/FcmController.java
  src/main/java/umc/puppymode/web/controller/KakaoLoginController.java
  src/main/java/umc/puppymode/web/dto/FCMDTO/FCMAppointmentRequestDTO.java
  src/main/java/umc/puppymode/web/dto/FCMDTO/FCMAppointmentResponseDTO.java
  src/main/java/umc/puppymode/web/dto/FCMDTO/FCMPlayRequestDTO.java
  src/main/java/umc/puppymode/web/dto/FCMDTO/FCMPlayResponseDTO.java
  src/main/java/umc/puppymode/web/dto/FCMDTO/FCMRequestDTO.java
  src/main/java/umc/puppymode/web/dto/FCMDTO/FCMResponseDTO.java
Labels: ✨ feature

#65 [Feat] 유저 강아지 삭제 기능 구현 #63
  src/main/java/umc/puppymode/service/MainPuppyService/MainPuppyCommandService.java
  src/main/java/umc/puppymode/service/MainPuppyService/MainPuppyCommandServiceImpl.java
  src/main/java/umc/puppymode/web/controller/MainPuppyController.java
Labels: ✨ feature

#68 Refactor/#66 appointment jwt
  src/main/java/umc/puppymode/repository/DrinkingAppointmentRepository.java
  src/main/java/umc/puppymode/service/DrinkingAppointmentService/DrinkingAppointmentCommendService.java
  src/main/java/umc/puppymode/service/DrinkingAppointmentService/DrinkingAppointmentCommendServiceImpl.java
  src/main/java/umc/puppymode/service/DrinkingAppointmentService/DrinkingAppointmentQueryService.java
  src/main/java/umc/puppymode/service/DrinkingAppointmentService/DrinkingAppointmentQueryServiceImpl.java
  src/main/java/umc/puppymode/service/LocationService/LocationService.java
  src/main/java/umc/puppymode/service/LocationService/LocationServiceImpl.java
  src/main/java/umc/puppymode/web/controller/DrinkingAppointmentController.java
Labels: ♻️ refactor

#77 [REFACTOR] add isNewUser field to LoginResponseDTO #61
  src/main/java/umc/puppymode/config/security/JwtTokenProvider.java
  src/main/java/umc/puppymode/service/UserService/UserAuthServiceImpl.java
  src/main/java/umc/puppymode/web/dto/LoginResponseDTO.java
  src/main/java/umc/puppymode/web/dto/UserInfoResponseDTO.java
Labels: ♻️ refactor

#78 Feat/#49 user management
  src/main/java/umc/puppymode/config/security/JwtAuthenticationFilter.java
  src/main/java/umc/puppymode/config/security/JwtTokenProvider.java
  src/main/java/umc/puppymode/domain/User.java
  src/main/java/umc/puppymode/repository/UserRepository.java
  src/main/java/umc/puppymode/service/AuthService/KakaoService.java
  src/main/java/umc/puppymode/service/UserService/UserAuthServiceImpl.java
  src/main/java/umc/puppymode/service/UserService/UserInfoService.java
  src/main/java/umc/puppymode/service/UserService/UserInfoServiceImpl.java
  src/main/java/umc/puppymode/web/controller/KakaoLoginController.java
  src/main/java/umc/puppymode/web/controller/UserController.java
  src/main/java/umc/puppymode/web/dto/UserInfoResponseDTO.java
Labels: ✨ feature

#79 Feat/#49 user management
  src/main/java/umc/puppymode/domain/User.java
  src/main/java/umc/puppymode/repository/UserRepository.java
  src/main/java/umc/puppymode/service/UserService/UserAuthServiceImpl.java
  src/main/java/umc/puppymode/service/UserService/UserInfoServiceImpl.java
  src/main/java/umc/puppymode/service/UserService/UserWithdrawService.java
  src/main/java/umc/puppymode/service/UserService/UserWithdrawServiceImpl.java
  src/main/java/umc/puppymode/web/controller/UserWithdrawController.java
Labels: ✨ feature

#82 [Feat] 강아지 정보 조회 Response 수정 #81
  src/main/java/umc/puppymode/converter/MainPuppyConverter.java
Labels: ✨ feature

#85 [FEAT] 아이템 착용 해제 API 구현 #83
  src/main/java/umc/puppymode/service/PuppyService/PuppyItemService.java
  src/main/java/umc/puppymode/service/PuppyService/PuppyItemServiceImpl.java
  src/main/java/umc/puppymode/web/controller/PuppyItemController.java
Labels: ✨ feature

#86 Bug/#84 fcm notification fix
  src/main/java/umc/puppymode/apiPayload/code/status/SuccessStatus.java
  src/main/java/umc/puppymode/service/FcmService/FcmAppointmentServiceImpl.java
  src/main/java/umc/puppymode/service/FcmService/FcmPlaytimeServiceImpl.java
  src/main/java/umc/puppymode/service/FcmService/FcmServiceImpl.java
Labels: 🐛 bug

#87 [FEAT] 음주 달력 관련 API 구현 #74
  src/main/java/umc/puppymode/domain/DrinkHistory.java
  src/main/java/umc/puppymode/repository/DrinkHistoryItemRepository.java
  src/main/java/umc/puppymode/repository/DrinkHistoryRepository.java
  src/main/java/umc/puppymode/repository/FeedRepository.java
  src/main/java/umc/puppymode/service/CalenderService/CalenderQueryService.java
  src/main/java/umc/puppymode/service/CalenderService/CalenderQueryServiceImpl.java
  src/main/java/umc/puppymode/web/controller/CalenderController.java
  src/main/java/umc/puppymode/web/dto/CalenderDTO/CalenderListResponseDTO.java
  src/main/java/umc/puppymode/web/dto/CalenderDTO/CalenderResponseDTO.java
  src/main/java/umc/puppymode/web/dto/CalenderDTO/DrinkHistoryItemDTO.java
  src/main/java/umc/puppymode/web/dto/CalenderDTO/FeedDTO.java
Labels: ✨ feature

#89 [FEAT] 애니메이션 프레임 조회 API 구현 #39
  src/main/java/umc/puppymode/domain/PuppyAnimation.java
  src/main/java/umc/puppymode/domain/PuppyAnimationImage.java
  src/main/java/umc/puppymode/domain/enums/AnimationType.java
  src/main/java/umc/puppymode/repository/PuppyAnimationRepository.java
  src/main/java/umc/puppymode/service/PuppyService/PuppyAnimationService.java
  src/main/java/umc/puppymode/service/PuppyService/PuppyAnimationServiceImpl.java
  src/main/java/umc/puppymode/service/PuppyService/PuppyItemServiceImpl.java
  src/main/java/umc/puppymode/web/controller/PuppyAnimationController.java
  src/main/java/umc/puppymode/web/dto/AnimationFramesResponseDTO.java
Labels: ✨ feature

#93 Refactor/#91 remove appointment reschedule
  src/main/java/umc/puppymode/service/DrinkingAppointmentService/DrinkingAppointmentCommendService.java
  src/main/java/umc/puppymode/service/DrinkingAppointmentService/DrinkingAppointmentCommendServiceImpl.java
  src/main/java/umc/puppymode/web/controller/DrinkingAppointmentController.java
  src/main/java/umc/puppymode/web/dto/DrinkingAppointmentRequestDTO.java
  src/main/java/umc/puppymode/web/dto/DrinkingAppointmentResponseDTO.java
Labels: ♻️ refactor

#95 [MOD] securityConfig 수정 #94
  src/main/java/umc/puppymode/config/security/SecurityConfig.java
Labels: 🐛 bug

#100 Feat/#97 appointment drinking duration
  src/main/java/umc/puppymode/domain/DrinkingAppointment.java
  src/main/java/umc/puppymode/service/DrinkingAppointmentService/DrinkingAppointmentQueryService.java
  src/main/java/umc/puppymode/service/DrinkingAppointmentService/DrinkingAppointmentQueryServiceImpl.java
  src/main/java/umc/puppymode/service/LocationService/LocationServiceImpl.java
  src/main/java/umc/puppymode/web/controller/DrinkingAppointmentController.java
  src/main/java/umc/puppymode/web/dto/DrinkingAppointmentResponseDTO.java
Labels: ✨ feature
