Repository PuppyMode-org/PuppyMode-Server, pull requests merged in 2025-02, with the labels that each got.

#104 [Feat] 컬렉션 업데이트 및 아이템 획득 기능 구현 #103
  src/main/java/umc/puppymode/apiPayload/code/status/ErrorStatus.java
  src/main/java/umc/puppymode/domain/mapping/PuppyCustomization.java
  src/main/java/umc/puppymode/domain/mapping/UserCollection.java
  src/main/java/umc/puppymode/repository/UserCollectionRepository.java
  src/main/java/umc/puppymode/service/DrinkService/DrinkCommandServiceImpl.java
  src/main/java/umc/puppymode/service/MainPuppyService/MainPuppyQueryServiceImpl.java
  src/main/java/umc/puppymode/service/PuppyService/PuppyItemServiceImpl.java
  src/main/java/umc/puppymode/service/UserCollectionService/UserCollectionCommandService.java
  src/main/java/umc/puppymode/service/UserCollectionService/UserCollectionCommandServiceImpl.java
  src/main/java/umc/puppymode/service/UserService/UserQueryServiceImpl.java
Labels: ✨ feature

#109 Refactor/#106 appointment time format
  src/main/java/umc/puppymode/service/DrinkingAppointmentService/DrinkingAppointmentQueryService.java
  src/main/java/umc/puppymode/web/controller/DrinkingAppointmentController.java
  src/main/java/umc/puppymode/web/dto/DrinkingAppointmentResponseDTO.java
Labels: ♻️ refactor

#108 [Refactor] puppyId 필요 시 JWT 사용 리팩토링 #105
  src/main/java/umc/puppymode/repository/PuppyRepository.java
  src/main/java/umc/puppymode/service/MainPuppyService/MainPuppyCommandService.java
  src/main/java/umc/puppymode/service/MainPuppyService/MainPuppyCommandServiceImpl.java
  src/main/java/umc/puppymode/web/controller/MainPuppyController.java
Labels: ♻️ refactor

#111 [Feat] 강아지 hard delete 및 생성 api 수정 #110
  src/main/java/umc/puppymode/converter/MainPuppyConverter.java
  src/main/java/umc/puppymode/repository/PuppyCustomizationRepository.java
  src/main/java/umc/puppymode/service/MainPuppyService/MainPuppyCommandServiceImpl.java
Labels: ✨ feature

#114 [Refactor] Puppy에 Image URL 추가 #112
  src/main/java/umc/puppymode/converter/MainPuppyConverter.java
  src/main/java/umc/puppymode/domain/Puppy.java
  src/main/java/umc/puppymode/service/FcmService/FcmPlaytimeServiceImpl.java
Labels: ✨ feature, ♻️ refactor

#115 [FEAT] 강아지 꾸미기 관련 API 추가 #113
  src/main/java/umc/puppymode/service/PuppyService/PuppyItemService.java
  src/main/java/umc/puppymode/service/PuppyService/PuppyItemServiceImpl.java
  src/main/java/umc/puppymode/web/controller/PuppyItemController.java
  src/main/java/umc/puppymode/web/dto/PuppyCustomDTO/EquippedItemInfoDTO.java
  src/main/java/umc/puppymode/web/dto/PuppyCustomDTO/ItemCategoryResponseDTO.java
  src/main/java/umc/puppymode/web/dto/PuppyCustomDTO/ItemResponseDTO.java
Labels: ✨ feature

#117 [FEAT] 착용 아이템 목록 조회 API 구현 #116
  src/main/java/umc/puppymode/repository/PuppyCustomizationRepository.java
  src/main/java/umc/puppymode/service/PuppyService/PuppyItemService.java
  src/main/java/umc/puppymode/service/PuppyService/PuppyItemServiceImpl.java
  src/main/java/umc/puppymode/web/controller/PuppyItemController.java
  src/main/java/umc/puppymode/web/dto/PuppyCustomDTO/EquippedItemInfoDTO.java
Labels: ✨ feature

#120 [REFACTOR] 아이템 착용 관련 로직 수정 #119
  src/main/java/umc/puppymode/service/PuppyService/PuppyItemServiceImpl.java
  src/main/java/umc/puppymode/web/controller/PuppyItemController.java
Labels: ✨ feature

#126 Refactor/#124 cleanup and typo fix
  src/main/java/umc/puppymode/converter/TempConverter.java
  src/main/java/umc/puppymode/domain/NotificationCategory.java
  src/main/java/umc/puppymode/domain/Temp.java
  src/main/java/umc/puppymode/domain/UserPolicyType.java
  src/main/java/umc/puppymode/domain/enums/Temp.java
  src/main/java/umc/puppymode/domain/mapping/Temp.java
  src/main/java/umc/puppymode/domain/mapping/UserNotification.java
  src/main/java/umc/puppymode/domain/mapping/UserPolicy.java
  src/main/java/umc/puppymode/repository/DrinkHistoryItemRepository.java
  src/main/java/umc/puppymode/repository/DrinkHistoryRepository.java
  src/main/java/umc/puppymode/repository/FeedRepository.java
  src/main/java/umc/puppymode/repository/TempRepository.java
  src/main/java/umc/puppymode/service/CalendarService/CalendarQueryService.java
  src/main/java/umc/puppymode/service/CalendarService/CalendarQueryServiceImpl.java
  src/main/java/umc/puppymode/service/CalenderService/CalenderQueryService.java
  src/main/java/umc/puppymode/service/TempService/TempCommandService.java
  src/main/java/umc/puppymode/service/TempService/TempCommandServiceImpl.java
  src/main/java/umc/puppymode/service/TempService/TempQueryService.java
  src/main/java/umc/puppymode/service/TempService/TempQueryServiceImpl.java
  src/main/java/umc/puppymode/web/controller/CalendarController.java
  src/main/java/umc/puppymode/web/controller/CalenderController.java
  src/main/java/umc/puppymode/web/controller/TempController.java
  src/main/java/umc/puppymode/web/dto/CalendarDTO/CalendarListResponseDTO.java
  src/main/java/umc/puppymode/web/dto/CalendarDTO/CalendarResponseDTO.java
  src/main/java/umc/puppymode/web/dto/CalendarDTO/DrinkHistoryItemDTO.java
  src/main/java/umc/puppymode/web/dto/CalendarDTO/FeedDTO.java
  src/main/java/umc/puppymode/web/dto/TempRequestDTO.java
  src/main/java/umc/puppymode/web/dto/TempResponseDTO.java
Labels: ♻️ refactor

#127 Feat/#125 ranking friends
  src/main/java/umc/puppymode/config/security/JwtAuthenticationFilter.java
  src/main/java/umc/puppymode/repository/UserAuthRepository.java
  src/main/java/umc/puppymode/service/AuthService/KakaoAuthService.java
  src/main/java/umc/puppymode/service/AuthService/UserAuthServiceImpl.java
  src/main/java/umc/puppymode/service/RankingService/RankingQueryService.java
  src/main/java/umc/puppymode/service/RankingService/RankingQueryServiceImpl.java
  src/main/java/umc/puppymode/service/UserService/UserInfoServiceImpl.java
  src/main/java/umc/puppymode/web/controller/KakaoAuthController.java
  src/main/java/umc/puppymode/web/controller/RankingController.java
  src/main/java/umc/puppymode/web/dto/KakaoFriendsResponseDTO.java
  src/main/java/umc/puppymode/web/dto/LoginResponseDTO.java
  src/main/java/umc/puppymode/web/dto/UserInfoResponseDTO.java
Labels: ✨ feature

#133 Refactor/#128 puppy item error
  src/main/java/umc/puppymode/apiPayload/code/status/ErrorStatus.java
  src/main/java/umc/puppymode/service/PuppyService/PuppyAnimationServiceImpl.java
  src/main/java/umc/puppymode/service/PuppyService/PuppyItemServiceImpl.java
Labels: ♻️ refactor

#134 [FEAT] 애니메이션 프레임 조회 API 수정 #132
  src/main/java/umc/puppymode/PuppymodeApplication.java
  src/main/java/umc/puppymode/domain/PuppyAnimation.java
  src/main/java/umc/puppymode/domain/enums/AnimationType.java
  src/main/java/umc/puppymode/repository/PuppyAnimationRepository.java
  src/main/java/umc/puppymode/service/PuppyService/PuppyAnimationService.java
  src/main/java/umc/puppymode/service/PuppyService/PuppyAnimationServiceImpl.java
  src/main/java/umc/puppymode/web/controller/PuppyAnimationController.java
Labels: ✨ feature

#139 Feat/#137 appointment nearest scheduled
  src/main/java/umc/puppymode/repository/DrinkingAppointmentRepository.java
  src/main/java/umc/puppymode/service/DrinkingAppointmentService/DrinkingAppointmentQueryService.java
  src/main/java/umc/puppymode/service/DrinkingAppointmentService/DrinkingAppointmentQueryServiceImpl.java
  src/main/java/umc/puppymode/web/controller/DrinkingAppointmentController.java
Labels: ✨ feature

#142 [REFACTOR] 먹이 이미지 변경 #141
  src/main/java/umc/puppymode/domain/enums/FeedingItem.java
Labels: ♻️ refactor

#143 Refactor/#122 calender
  src/main/java/umc/puppymode/service/CalendarService/CalendarQueryServiceImpl.java
  src/main/java/umc/puppymode/web/dto/CalendarDTO/CalendarResponseDTO.java
Labels: ♻️ refactor

#148 [Refactor] 강아지 랜덤선택 API 피드백 반영 #136
  src/main/java/umc/puppymode/web/controller/MainPuppyController.java
Labels: ♻️ refactor

#153 [CI] 애플 로그인 관련 설정 추가_2 #151
  .github/workflows/cicd.yml
Labels: 🚀 ci

#150 [REFACTOR] 가장 가까운 SCHEDULED 상태의 약속 조회하기 API 수정 #149
  src/main/java/umc/puppymode/repository/DrinkingAppointmentRepository.java
Labels: ♻️ refactor

#147 Feat/#80 apple login
  .gitignore
  src/main/java/umc/puppymode/config/AppleAuthConfig.java
  src/main/java/umc/puppymode/config/WebClientConfig.java
  src/main/java/umc/puppymode/config/security/JwtAuthenticationFilter.java
  src/main/java/umc/puppymode/config/security/JwtTokenProvider.java
  src/main/java/umc/puppymode/service/AuthService/AppleAuthCommandService.java
  src/main/java/umc/puppymode/service/AuthService/AppleAuthCommandServiceImpl.java
  src/main/java/umc/puppymode/service/AuthService/AppleAuthQueryService.java
  src/main/java/umc/puppymode/service/AuthService/AppleAuthQueryServiceImpl.java
  src/main/java/umc/puppymode/service/AuthService/AppleKeyService.java
  src/main/java/umc/puppymode/service/AuthService/AppleKeyServiceImpl.java
  src/main/java/umc/puppymode/service/AuthService/ApplePublicKeyUtil.java
  src/main/java/umc/puppymode/service/AuthService/KakaoAuthService.java
  src/main/java/umc/puppymode/service/AuthService/UserAuthServiceImpl.java
  src/main/java/umc/puppymode/web/controller/AppleAuthController.java
  src/main/java/umc/puppymode/web/dto/AppleLoginRequestDTO.java
  src/main/java/umc/puppymode/web/dto/AppleTokenResponseDTO.java
  src/main/java/umc/puppymode/web/dto/LoginResponseDTO.java
Labels: ✨ feature

#157 [CI] 애플 시크릿 키파일 로드 방식 변경 #156
  .github/workflows/cicd.yml
  src/main/java/umc/puppymode/config/AppleAuthConfig.java
  src/main/java/umc/puppymode/service/AuthService/AppleKeyServiceImpl.java
Labels: 🚀 ci

#158 [CI] 애플 시크릿 키파일 로드 방식 변경_2 #156
  .github/workflows/cicd.yml
Labels: 🚀 ci

#159 [CI] 애플 시크릿 키파일 로드 방식 변경_3 #156
  .github/workflows/cicd.yml
  src/main/java/umc/puppymode/service/AuthService/AppleKeyServiceImpl.java
Labels: 🚀 ci

#160 [CI] 애플 시크릿 키파일 로드 방식 변경_3 #156
  .github/workflows/cicd.yml
  src/main/java/umc/puppymode/config/AppleAuthConfig.java
  src/main/java/umc/puppymode/service/AuthService/AppleKeyServiceImpl.java
Labels: 🚀 ci

#164 [REFACTOR] 음주 기록 및 먹이 주기 강아지 부분 수정
  src/main/java/umc/puppymode/service/DrinkService/DrinkCommandServiceImpl.java
  src/main/java/umc/puppymode/web/dto/DrinkResponseDTO.java
Labels: ♻️ refactor

#165 Feat/#80 apple login
  src/main/java/umc/puppymode/config/AppleAuthConfig.java
  src/main/java/umc/puppymode/config/security/SecurityConfig.java
  src/main/java/umc/puppymode/service/AuthService/AppleAuthCommandService.java
  src/main/java/umc/puppymode/service/AuthService/AppleAuthCommandServiceImpl.java
  src/main/java/umc/puppymode/service/AuthService/AppleAuthQueryService.java
  src/main/java/umc/puppymode/service/AuthService/AppleAuthQueryServiceImpl.java
  src/main/java/umc/puppymode/web/controller/AppleAuthController.java
  src/main/java/umc/puppymode/web/dto/AppleLoginRequestDTO.java
Labels: ♻️ refactor

#168 Refactor/#166 calender
  src/main/java/umc/puppymode/service/CalendarService/CalendarQueryServiceImpl.java
  src/main/java/umc/puppymode/service/DrinkService/DrinkCommandServiceImpl.java
Labels: ♻️ refactor

#171 Refactor/#169 appointment add location name
  src/main/java/umc/puppymode/converter/DrinkingAppointmentConverter.java
  src/main/java/umc/puppymode/web/dto/DrinkingAppointmentResponseDTO.java
Labels: ♻️ refactor

#172 [REFACTOR] endpoint 임시 수정 #163
  src/main/java/umc/puppymode/web/controller/AppleAuthController.java
Labels: ♻️ refactor

#174 [BUG] 생성자 삭제 #163
  src/main/java/umc/puppymode/service/AuthService/AppleKeyServiceImpl.java
Labels: 🐛 bug

#175 [REFACTOR] 웹용으로 client id 변경 #163
  src/main/java/umc/puppymode/service/AuthService/AppleAuthQueryServiceImpl.java
Labels: 🐛 bug

#180 [REFACTOR] 캘린더 조회 시 전체 날짜 반환하도록 수정 #179
  src/main/java/umc/puppymode/service/CalendarService/CalendarQueryServiceImpl.java
Labels: ♻️ refactor

#181 Refactor/#155 drink record
  src/main/java/umc/puppymode/domain/enums/FeedingItem.java
  src/main/java/umc/puppymode/service/CalendarService/CalendarQueryServiceImpl.java
  src/main/java/umc/puppymode/service/DrinkService/DrinkCommandServiceImpl.java
  src/main/java/umc/puppymode/service/DrinkService/DrinkQueryServiceImpl.java
  src/main/java/umc/puppymode/web/dto/CalendarDTO/CalendarResponseDTO.java
  src/main/java/umc/puppymode/web/dto/DrinkResponseDTO.java
Labels: ♻️ refactor

#183 [REFACTOR] 캘린더 조회 시 오늘 이후에 대한 status 수정 #179
  src/main/java/umc/puppymode/service/CalendarService/CalendarQueryServiceImpl.java
Labels: ♻️ refactor

#185 [REFACTOR] 캘린더 조회 시 status가 오늘 날짜를 포함하여 나타나도록 수정 #184
  src/main/java/umc/puppymode/service/CalendarService/CalendarQueryServiceImpl.java
Labels: ♻️ refactor

#189 [REFACTOR] 내 주량 정보 조회 API 수정
  src/main/java/umc/puppymode/service/DrinkService/DrinkQueryServiceImpl.java
  src/main/java/umc/puppymode/web/controller/DrinkController.java
Labels: ♻️ refactor

#191 [REFACTOR] 내 주량 정보 조회 API 수정
  src/main/java/umc/puppymode/service/DrinkService/DrinkQueryServiceImpl.java
  src/main/java/umc/puppymode/web/dto/DrinkResponseDTO.java
Labels: ♻️ refactor

#192 Feat/#80 apple login
  src/main/java/umc/puppymode/config/AppleAuthConfig.java
  src/main/java/umc/puppymode/service/AuthService/AppleAuthCommandServiceImpl.java
  src/main/java/umc/puppymode/service/AuthService/AppleKeyService.java
  src/main/java/umc/puppymode/service/AuthService/AppleKeyServiceImpl.java
Labels: 🐛 bug

#193 [REFACTOR] 앱 클라이언트에 맞게 수정 #163
  src/main/java/umc/puppymode/service/AuthService/AppleAuthCommandServiceImpl.java
  src/main/java/umc/puppymode/service/AuthService/AppleAuthQueryServiceImpl.java
  src/main/java/umc/puppymode/web/controller/AppleAuthController.java
  src/main/java/umc/puppymode/web/dto/AppleLoginRequestDTO.java
Labels: ♻️ refactor

#194 [REFACTOR] 웹 애플 로그인 시 email 저장 로직 추가 #163
  src/main/java/umc/puppymode/service/AuthService/AppleAuthCommandService.java
  src/main/java/umc/puppymode/service/AuthService/AppleAuthCommandServiceImpl.java
  src/main/java/umc/puppymode/web/controller/AppleAuthController.java
Labels: ♻️ refactor
